### ISSUE TITLE
where delay ?

### ISSUE THREAD

**Issue by dzanis** [bagxi/stm8s-ds18b20#1]
https://github.com/bagxi/stm8s-ds18b20/blob/6555e4cd6d891211467a5ff52be1876a59d9ac09/src/one_wire.h#L22

**Comment by bagxi** [comment]
'delay.h'/'delay.cpp' wasn't written by me. Sorry but the author doesn't want to publish this part of the code. :(
But if you need I can help.

**Comment by dzanis** [comment]
Thank you, i found   https://github.com/Hoksmur/stm8_routines/blob/master/delay.h
